### PR TITLE
将SCS升级到.net standard 2.0

### PR DESCRIPTION
**Pull request by NeedJustWord**

### CODE REVIEW

**Comment by NeedJustWord** [comment]
I fixed a bug about Disconnect on commit 8bf6fa8cc3ebe010b27a3f63081147cbc1bcf147

**Comment by erkantaylan** [comment]
Hello sir, I am tying to test your PR, but I am getting error, I am currently testing on DotNet Core 2.2
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.Remoting.Proxies.RealProxy' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=Scs
  StackTrace:
   at Hik.Communication.ScsServices.Client.ScsServiceClient`1..ctor(IScsClient client, Object clientObject)
   at Hik.Communication.ScsServices.Client.ScsServiceClientBuilder.CreateClient[T](ScsEndPoint endpoint, Object clientObject)
   at Eys.Service.Scs.ScsClientService..ctor(String ip, UInt16 port) in C:\Projects\ALTERNET\ecz-auto\Eys\Eys\Eys.Service\Scs\ScsClientService.cs:line 15
   at Eys.Service.Program.Main(String[] args) in C:\Projects\ALTERNET\ecz-auto\Eys\Eys\Eys.Service\Program.cs:line 18
```

My code 
```C#
var endPoint = new ScsTcpEndPoint("localhost", 20000);
client = ScsServiceClientBuilder.CreateClient<IRemoteService>(endPoint); /*<-- error line*/

[ScsService]
public interface IRemoteService {
    string Ping(string message);
    string Login(string username, string password);
}
```

**Comment by NeedJustWord** [comment]
> Hello sir, I am tying to test your PR, but I am getting error, I am currently testing on DotNet Core 2.2
> 
> ```
> System.TypeLoadException
>   HResult=0x80131522
>   Message=Could not load type 'System.Runtime.Remoting.Proxies.RealProxy' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
>   Source=Scs
>   StackTrace:
>    at Hik.Communication.ScsServices.Client.ScsServiceClient`1..ctor(IScsClient client, Object clientObject)
>    at Hik.Communication.ScsServices.Client.ScsServiceClientBuilder.CreateClient[T](ScsEndPoint endpoint, Object clientObject)
>    at Eys.Service.Scs.ScsClientService..ctor(String ip, UInt16 port) in C:\...\ScsClientService.cs:line 15
>    at Eys.Service.Program.Main(String[] args) in C:\...\Program.cs:line 18
> ```
> 
> My code
> 
> ```cs
> var endPoint = new ScsTcpEndPoint("localhost", 20000);
> client = ScsServiceClientBuilder.CreateClient<IRemoteService>(endPoint); /*<-- error line*/
> 
> [ScsService]
> public interface IRemoteService {
>     string Ping(string message);
>     string Login(string username, string password);
> }
> ```

DotNet Core uses Scs.Core instead of Scs

**Comment by hikalkan** [comment]
Thanks for your implementation. I am late to merge, but better than never :) I will test it, then publish the package.

**Comment by Sire** [comment]
We are using this version in production now. We had to implement this fix however: https://github.com/hikalkan/scs/issues/43
When that is fixed, I recommend you publish @hikalkan 

Thanks for a great library! 😀

**Comment by oleksandr-kostian** [comment]
@hikalkan Why don't you want to update the new version in Nuget . They are compatible with framework version. I tested it and it seems like it works well.

**Pull request merged**
